### PR TITLE
Version, changelog and resizable sidebar

### PR DESCRIPTION
**Pull request by boeckMt**
Issues: 
- closses #80 
- closses #81
- closses #70

### CODE REVIEW

**Comment by MichaelLangbein** [comment]
Worked perfectly on my machine - thanks a lot!
Is this ready to merge?

**Review by MichaelLangbein — APPROVED** [review]
Better than how ExpressionChangedAfterChecked was fixed in master.

**Comment by boeckMt** [comment]
> Worked perfectly on my machine - thanks a lot! Is this ready to merge?

**I had to adjust some stuff a bit:**

**1. Theme**
- Separate them in css files and load them lazy // The old class selector changed the hierarchy so some styles where not working anymore. This caused problems adding the responsive nav.

**2. Configuration Wizard**
- Due to the `clr-vertical-nav` was in a component, some styles and functions for the vertical nav resize did not work. Now the async processes are fetched in route map and pased to the Configuration Wizard as input. This way we can check if the processes are available and then create nav groups.


@MichaelLangbein can you check that this is not breaking any old functionality.

**Comment by MichaelLangbein** [comment]
As for the config wizard: it's weird how clr-vertical-nav does not seem to handle async child elements on its own (at least not when they are in a child component). But passing them from the outside is a fair solution. Haven't seen any breakage anywhere.

About the theme: was that change in clarity or is this in the css written in riesgos? (In the latter case we have all freedom to change things as necessary, of course)

**Pull request merged**
